### PR TITLE
Added Chimu mirror

### PR DESCRIPTION
**Pull request by Naozumi520**
Since bloodcat has been shutdown, we can't enjoy of it's download speed anymore. But there's a succesor of bloodcat call chimu(chimu.moe). I have added it and tested it out and it works great! :)

### CODE REVIEW

**Comment by Naozumi520** [comment]
Url has been changed

**Comment by Mempler** [comment]
@Naozumi520 It did not ?

**Comment by Naozumi520** [comment]
hmmm
Chimu.moe/d/ 
not working?

**Comment by Naozumi520** [comment]
but the author said he don't accept pull requests anymore so (

**Comment by Mempler** [comment]
@Naozumi520 if you would be in chimu discord you would see that chimu is in maintenance mode right now.

**Comment by Naozumi520** [comment]
Oh i'm in there, Thanks! :)

**Pull request closed without merging**
